# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build_test_docker:
    docker:
      - image: circleci/golang:1.12.5
      
    working_directory: ~/iotex-antenna-go
#    environment:
#      - GOPATH: "${HOME}/go"
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v1-{{ checksum "go.sum" }}
      - run:
          name: go mod
          command: |
            export PATH=$PATH:/usr/local/go/bin
            go mod download
            go mod vendor
      - save_cache:
          key: go-mod-v1-{{ checksum "go.sum" }}
          paths:
              - ~/go/pkg/mod
      - run: go get golang.org/x/lint/golint
      - run: golint -set_exit_status $(go list ./... | grep -v /vendor/)
      - run: go vet $(go list ./... | grep -v /vendor/)
      - run: 
          name: go test
          command: |
            export GOPATH=/go
            set -e 
            for d in $(go list ./...|grep -v vendor); do
              go test -short -v -coverprofile=profile.out -covermode=count "$d"
              if [ -f profile.out ]; then
                cat profile.out >> coverage.txt
                rm profile.out
              fi
            done
          
workflows:
  version: 2
  commit:
    jobs:
      - build_test_docker
